### ISSUE TITLE
Add a command to add a quote

### ISSUE THREAD

**Issue by Xanawatt** [Xanawatt/Xana-Cogs#7]
\quote add <quote>

**Comment by Gimlie102** [comment]
Would this be restricted to admins?

**Comment by Xanawatt** [comment]
yes, it can be restricted to admins and/or trusted individuals

**Comment by Gimlie102** [comment]
Cool, also in regards to this and #6 : if you want to make #3 happen you may want to add an operator to these commands so they aren't interpreted as keywords. such as "\quote -add"

**Comment by Xanawatt** [comment]
Fully implemented in 8826a095ad925d5be2627e53ce301a018c573a15
